[package]
name = "aerolithdb-security"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
dryoc = { workspace = true }
ring = { workspace = true }
